import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { FolderClosed, Heart, Image } from 'lucide-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Button } from '../components/ui/button';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function SideMenu() {
  return (
    <div className='pb-12 w-1/5'>
      <div className='space-y-4 py-4'>
        <div className='px-3 py-2'>
          <h2 className='mb-2 px-4 text-lg font-semibold tracking-tight'>
            Manage
          </h2>
          <div className='space-y-1'>
            <Button variant='secondary' className='w-full justify-start gap-2'>
              <Image />
              Gallery
            </Button>
            <Button variant='ghost' className='w-full justify-start gap-2'>
              <FolderClosed />
              Albums
            </Button>
            <Button variant='ghost' className='w-full justify-start gap-2'>
              <Heart />
              Favorites
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='dark'>
      <body className={inter.className}>
        <div className='border-b'>
          <div className='flex h-16 items-center px-6 container mx-auto'>
            {/* <TeamSwitcher /> */}
            {/* <MainNav className="mx-6" /> */}
            App Icon
            <div className='ml-auto flex items-center space-x-4'>
              {/* <Search />
              <UserNav /> */}
              <Avatar>
                <AvatarImage
                  src='https://github.com/shadcn.png'
                  alt='@shadcn'
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className='flex'>
          <SideMenu />
          <div className='w-full p-4'>{children}</div>
        </div>
      </body>
    </html>
  );
}
